KumoCorp/kumomta

- crates/message/src/message.rs
- docs/reference/message/remove_all_named_headers.md
To support removal of any header the remove_all_named_header is exported in Lua. This can be used to remove bogus headers added by internal applications, for example Return-Path.
> Add method remove_all_named_header in lua

- assets/policy-extras/rollup.lua
- crates/kumod/src/ready_queue.rs
- crates/kumod/src/smtp_dispatcher.rs
- docs/reference/kumo/make_queue_config.md
- docs/userguide/policy/routing.md
add a hashmap of ip, domains to have the canonical name for tls connection and avoid the error: rust invalid peer certificate: NotValidForName when enable_tls is not "Disabled" or "OpportunisticInsecure"
> add mx_list_ip_map to smtp protocole for tls connection

- assets/policy-extras/log_hooks.lua
- assets/policy-extras/shaping.lua
Don't queue if reception_protocol == 'LogRecord'
> use logRecord reception_protocol to avoid loop

- crates/kumod/src/logging.rs
To keep it the same as headers, only add meta to logs if they are not null.
> only add meta to log if not null

- assets/policy-extras/dkim_sign.lua
- crates/message/src/dkim.rs
add default to dkim over_sign so it doesn't break deserialization if over_sign is not set.
> add default to dkim over_sign

- crates/kumod/src/lua_deliver.rs
Don't create clients on every webhook call and reuse the existing one.
> reuse connection for lua deliveries

- assets/policy-extras/queue.lua
resolve_config skips all table fields in the queues.toml config subsection, so  adding a protocol field in any of the sections other than [queue.default] gets ignored.
Added an exception in the queue.lua:resolve_config so "protocol" setting fields are not ignored in the the queues.toml  subsections.
> Update queue.lua to allow protocol field in queues.toml

- crates/rfc5321/src/client_types.rs
Added serde to change \r and \n to spaces in response content because If the content is multiline, the regex used for automation needs to use \\n to get the line break and dsn_rewrite only works on the first line.
> add serializer for response content field

- crates/kumod/src/logging.rs
- crates/kumod/src/metrics_helper.rs
Add READY_COUNT_GAUGE to the list of metrics to remove on site reap
> Remove ready_count metrics on site reap

- docker/kumod/Dockerfile
This ensures the same os base as cargo chef, which in theory should help minimize breaking changes. It also fixes a conflict with uid/gid 1000 that was present in the ubuntu base due to the ubuntu user/group being uid/gid 1000.
> Switch to debian bookwork for runtime docker image 

- crates/throttle/src/lib.rs
- crates/throttle/src/limit.rs
Use as_sec_f64 for more details, because the extend method fails if the expires value is the same. Also set redis-cell response to corresponding attributes.
> use nanoseconds in redis lease durations

- assets/policy-extras/log_hooks.lua
I believe connection:close was inserted in the wrong place and should be inside the constructor function with the connection object.
Using version 2024.07.24-84bc2f05 causes crash when calling log_hooks:new_json
> Patch bug in log_hooks.lua

- crates/kumod/src/queue.rs
Use the same order for the labels and add metric removal at the same time as the removal of the schedule_queue metric.
> swap label of scheduled_by_tenant_campaign

- crates/config/src/lib.rs
- crates/kumo-server-common/src/disk_space.rs
- crates/proxy-server/Cargo.toml
- crates/proxy-server/src/proxy_handler.rs
Fixes some minor issues that prevented `cargo check` from working on macOS, and a newish warning.
I assume keeping it compiling on macOS is a non-goal (so checking it in CI is not worth it), but these changes seem small enough that they're probably still worth it? (Would be nice for me at least.)
> Fix compilation on macOS

- assets/policy-extras/shaping.toml
Yahoo responds at times with DSNs such as "`421 4.7.0 [TSS04] messages from xxxx temporarily deferred due to`". This accounts for that as the general guidance for this type of response is to typically suspend delivery for 2-4 hours in the event of such a message.
This regex can be represented in multiple ways including "`\[TS?(S)04\]`", "`\[T(S|SS)04\]`", etc. As written, this was tested and validated with Golang, PCRE, PCRE2, Python, and Rust via Regex101.
> Amend Regex for Yahoo to suspend on both TS04 and TSS04 with the same duration of 2 hours.

- Cargo.lock
- crates/kumo-server-common/src/lib.rs
- crates/mod-redis/src/lib.rs
- crates/throttle/Cargo.toml
- crates/throttle/src/lib.rs
- crates/throttle/src/limit.rs
- crates/throttle/src/throttle.rs
Uses a Lua script for GCRA from https://github.com/Losant/redis-gcra/blob/master/lib/gcra.lua to perform the necessary logic without support for the redis-cell module that provides `CL.THROTTLE`.
Fixes #275.
> throttle: add support for Redis installs without redis-cell module

- .github/workflows/kumomta.yml
This runs the build on ubuntu only, capturing the debs as artifacts in the action run.
This is intended as a backstop for the main CI in case it is having issues.
> ci: add gh actions runner for pull requests only

- Cargo.lock
- crates/dns-resolver/Cargo.toml
- crates/dns-resolver/src/lib.rs
- crates/dns-resolver/src/resolver.rs
- crates/message/src/message.rs
- crates/mod-dns-resolver/src/lib.rs
- crates/mta-sts/src/dns.rs
@wez what do you think of this direction? Might make sense to review the last commit first, the rest is sort of smaller/obvious stuff to get to this. As next steps, I'd add an `impl` feature for the dns-resolver crate so that most dependencies don't need to pull in libunbound, then I can fold the crate-specific `Lookup` traits into the main `Resolver` trait.
> A trait-based resolver API

- .woodpecker/ubuntu.yml
This reverts commit 401df300998096ab208417f4f68b75ef1fdc3d03.
The docker merge step is failing:
```
envconfig.Process: assigning PULLREQUEST_DRONE_PULL_REQUEST to Number: converting '' to type int. details: strconv.ParseInt: parsing "": invalid syntax
```
It seems that the compatibility change in
https://github.com/woodpecker-ci/woodpecker/pull/3939 isn't sufficient.
Let's see if we can still run with the environment set manually, or if we'll need to blackjack our own woodpecker plugin for this.
https://github.com/KumoCorp/kumomta/issues/309
> Revert "ci: avoid deprecated syntax"

- Cargo.lock
- crates/dkim/src/public_key.rs
- crates/dkim/src/roundtrip_test.rs
- crates/dns-resolver/src/resolver.rs
- crates/integration-tests/spf-basic.lua
- crates/integration-tests/src/kumod.rs
- crates/integration-tests/src/test/mod.rs
- crates/integration-tests/src/test/spf_basic.rs
- crates/kumo-spf/src/lib.rs
- crates/kumo-spf/src/record.rs
- crates/kumo-spf/src/tests.rs
- crates/kumod/Cargo.toml
- crates/kumod/src/main.rs
- crates/kumod/src/smtp_server.rs
- crates/kumod/src/spf.rs
- crates/mod-dns-resolver/src/lib.rs
- docs/generate-toc.py
- docs/reference/kumo.spf/_index.md
- docs/reference/kumo.spf/check_host.md
Next step in #83. Currently untested.
r? @wez
> SPF: add basic SPF Lua API

- Cargo.lock
- crates/mod-kafka/Cargo.toml
- crates/mod-kafka/src/lib.rs
- docs/reference/kumo.kafka/_index.md
- docs/reference/kumo.kafka/build_producer.md
Add a new method to the kafka mod to also send with rdkafka's internal batching. The return is a bit strange because I couldn't figure out how to send the failed indexes as LuaError that could then be used in the lua part if it was caught with a pcall...
> add send_batch method to kafka mod

- assets/build-deb.sh
add unmask to enable switching between installs of kumomta and kumomta-dev and avoid: 
Failed to restart kumomta.service: Unit kumomta.service is masked.
Failed to restart kumo-tsa-daemon.service: Unit kumo-tsa-daemon.service is masked.
Also should the Conflicts field be changed to mail-transport-agent like described in the debian doc for mta? https://www.debian.org/doc/debian-policy/ch-customized-programs.html#mail-transport-delivery-and-user-agents
> Add unmask to deb postinst

- docs/faq/flush_queue.md
When executing the `kcli rebind` command, `--reason` is a [required argument](https://docs.kumomta.com/reference/rapidoc/?h=api#post-/api/admin/rebind/v1).
Running the command without a "reason" causes it to fail with an error message.
This copy edit to the documentation aligns the example command with its expected input.
> Modify `kcli` command example to match required arguments

- docs/userguide/clustering/scaling.md
I think it'd be helpful to also include over what protocol the rebind actually sends messages back into the queue. 
* Is the rebind talking through the load balancer over the same protocol that the messages was relayed to it ie: http or smtp
* Is there a special means in which it's communicating with the other server or does this command require additional authentication in order to communicate with the server on the other side of the load balancer?
This info might already be available and I just need to rtfm, in which case I'd want to link to that particular doc as well over here.
> Complete the missing part of the command

- examples/docker-swarm/compose.yaml
- examples/single-node-docker/compose.yaml
A warning message is displayed that the [version element is obsolete](https://docs.docker.com/reference/compose-file/version-and-name/) and should be removed.
> Remove Docker compose top-level version property

- docs/userguide/configuration/logging.md
The documentation for configuring logging shows an example of using the Mini Jinja templating engine to format a log record using a `template` parameter:
```lua
kumo.configure_local_logs {
-- ..
template = [[{{type}} id={{ id }}, from={{ sender }} code={{ code }} age={{ timestamp - created }}]],
}
```
In its current context, the above example will fail with an error message while parsing `init.lua`:
```
problem initializing: call init callback: deserialize error: unknown field `template`
```
The correct usage is to nest the template format string _within_ the `per_record` parameter as shown below:
```lua
kumo.configure_local_logs {
log_dir = '/var/log/kumomta',
max_segment_duration = '1 seconds',
per_record = {
Bounce = {
-- Instead of logging the json record, evaluate this
-- template …
```
> Clarify example of log format `template` usage for customization

- docs/userguide/configuration/domains.md
This fixes a small typo I stumbled on, according the API reference this should be `log_arf`
> Update user guide to replace 'log_fbl' with 'log_arf' in example

- assets/run-lua-test
- crates/integration-tests/dns-ptr.lua
- crates/mod-dns-resolver/src/lib.rs
- crates/mod-dns-resolver/test-dns-ptr.lua
- docs/reference/kumo.dns/lookup_ptr.md
Adding a function to use through lua to query PTR records.
This can be used to match against RBLs or create blocking policies against reverse domain.
Tested against both IPv4 and IPv6
> add lookup_ptr

- crates/cidr-map/src/map.rs
- crates/dkim/src/canonicalization.rs
- crates/kumo-prometheus/src/lib.rs
- crates/kumo-prometheus/src/registry.rs
- crates/kumod/src/egress_source.rs
- crates/kumod/src/http_server/inject_v1.rs
- crates/maildir/src/lib.rs
- crates/mailparsing/src/mimepart.rs
- crates/mailparsing/src/nom_utils.rs
- crates/rfc5321/src/client.rs
Fix up some lifetime hiding that's causing compiler warnings. This should help compilation output look a bit cleaner.
With this we should be down to zero warnings.
> Fix up current warnings

- crates/kumo-spf/src/lib.rs
Spotted a couple derives that didn't look like they were used.
This struct appears to largely be used as a helper rather than in the lua code itself (from what I could tell). Removing the derives didn't seem to impact the `make test`.
> Remove unnecessary derives

- crates/kumo-dmarc/src/types/record.rs
- crates/kumo-spf/src/lib.rs
- crates/kumo-spf/src/record.rs
- crates/kumo-spf/src/spec.rs
- crates/kumod/src/smtp_server.rs
- crates/throttle/src/throttle.rs
With Rust's `if` being an expression form, an idiomatic approach to expression conditionals (like the ternary operator in C) is to use `if` where you have a conditional output value.
The one exception you might use the `match` on bool pattern is if you want to require that both paths are checked, but in all the cases below, the `match` isn't needed for that reason.
> Fix up match on bools

- Cargo.lock
- crates/kumo-dmarc/Cargo.toml
- crates/kumo-dmarc/src/lib.rs
- crates/kumo-dmarc/src/tests.rs
- crates/kumo-dmarc/src/types/format.rs
- crates/kumo-dmarc/src/types/record.rs
- crates/kumo-dmarc/src/types/results.rs
- crates/kumod/Cargo.toml
- crates/kumod/src/dmarc.rs
- crates/kumod/src/main.rs
- crates/kumod/src/spf.rs
Begin laying the groundwork for DMARC support.
Please note:
- some of this carries over from SPF support so that we can align DMARC code-wise with the structure we had before. I suspect this will change as it matures
- the only implemented logic thus far is the SPF and DKIM alignment checks.
- lua registration is in this PR, but lua testing was moved out for simplicity.
> Initial DMARC support

- Cargo.lock
- crates/kumo-dmarc/Cargo.toml
- crates/kumo-dmarc/src/tests.rs
- crates/kumo-dmarc/src/types/record.rs
This adds initial support for `pct=` to the DMARC support. Currently, we pass the message with a message that it was skipped, though we may want to explore a status that lets us know the message was skipped.
Testing is fairly simple, using a large sampling test to ensure that the pct is kicking in and only testing x percent of the messages. This can fail if it finds an outlier run, which currently would lead to a spurious failure.
> Add support for dmarc pct
